---
title: "Data preparation_v01"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(feather)
library(taRifx)
```
## Prepare the meta data set

```{r}
# Calculate the size of the output matrix

maxh <- max(6, 8, 18, 13, 14, 48)
nfeat <- 42
nxx <- maxh
nmethods <- 9
nff <- nmethods * maxh
metacols <- c("st", "n", "h", "type", "period")
nmeta <- length(metacols)

```

```{r}
mat <- matrix(nrow = length(meta_M4), ncol = (nmeta + nfeat + nxx + nff))

# For each of the 99 995 rows in the dataset do
for (i in 1:length(meta_M4)) {
  row <- meta_M4[[i]]
  
  # Add in the meta data
  for (j in 1:nmeta) {
    if (j == 1) {
      mat[i, j] <- row[[metacols[j]]]
    } else {
      mat[i, j] <- as.numeric(row[[metacols[j]]])
    }
  }
  
  # Add in the features
  fs <- row$features
  for (f in 1:length(fs)) {
    mat[i, f + nmeta] <- as.numeric(fs[[f]])
  }
  
  # Add in actuals
  xx <- as.numeric(row$xx)
  xx <- c(xx, rep("", nxx - length(xx)))
  for (x in 1:nxx) {
    mat[i, x + nmeta + nfeat] <- xx[x]
  }
  
  # Add inn all forecasts for all models
  ff <- row$ff
  fout <- c()
  for (nmet in 1:9) {
    v2 <- as.numeric(ff[nmet, ])
    
    fout <- append(fout, c(v2, rep("", maxh - length(v2))))
  }
  
  start <- (nmeta + nfeat + nxx)
  mat[i, (start+1):(length(fout)+start)] <- fout
  
}

colnames <- c()
colnames <- append(colnames, metacols)
colnames <- append(colnames, names(meta_M4[[1]][["features"]]))

for (x in 1:nxx) {
  colnames <- append(colnames, paste("actual_", toString(x-1), sep = ""))
}

methods <- row.names(meta_M4[[1]]$ff)
for (name in methods) {
  for (x in 1:maxh) {
    colnames <- append(colnames, paste(name, "_", toString(x-1), sep = ""))
  }
}

mat <- rbind(colnames, mat)
```

```{r}
write.table(mat, file = "m4_meta_cleaned.csv", row.names = FALSE, dec = ".", sep = ";", col.names = FALSE)
```

```{r}
df <- as.data.frame(mat[2:nrow(mat),])
df <- remove.factors(df)
colnames(df) <- mat[1,]
write_feather(df, path = "m4_meta_cleaned.feather")
```


## Prepare the training and validation data set

```{r}
# Calculate the size of the output matrix

maxx <- 0

for (i in 1:length(meta_M4)) {
  maxx <- max(maxx, meta_M4[[i]]$n)
}


```

```{r}
mat_x <- matrix(nrow = length(meta_M4), ncol = maxx)

# For each of the 99 995 rows in the dataset do
for (i in 1:length(meta_M4)) {
  row <- meta_M4[[i]]
  
  # Add in the actual values from before n - h
  x <- as.numeric(row$x)
  x <- c(x, rep(NaN, maxx - length(x)))
  for (j in 1:maxx) {
    mat_x[i, j] <- x[j]
  }
}
```

```{r}
write.table(mat_x, file = "m4_series_cleaned.csv", row.names = FALSE, dec = ".", sep = ";", col.names = TRUE)
```

```{r}
df_x <- as.data.frame(mat_x)
df_x <- remove.factors(df_x)
write_feather(df_x, path = "m4_series_cleaned.feather")
```


